graph LR
  いのき --> ボンバイエ
  ボンバイエ --> いのき

%% pybotters
%% ccxt
%% backtesting
%% https://github.com/kernc/backtesting.py
%% machine learning
%% numpy
%% pandas
%% scipy
%% matplotlib
%% seaborn
%% sklearn
%% tensorflow
%% keras
%% tensorboard
%% tensorflow-probability
%% tensorflow-addons
%% tensorflow-data-validation
%% tensorflow-probability
%% eagerpy
%% vectorbt
%% pytorch
%% jax
%% freqtrade
%% freqtrade-bot
%% freqtrade-strategy
%% freqtrade-data
%% freqtrade-edge
%% freqtrade-indicator
%% freqtrade-strategy-backtesting
%% freqtrade-strategy-data
%% freqtrade-strategy-edge
%% freqtrade-strategy-indicator
%% freqtrade-strategy-machine-learning
%% freqtrade-strategy-pybotters
%% freqtrade-strategy-tensorflow
%% freqtrade-strategy-tensorflow-probability
%% freqtrade-strategy-tensorflow-addons
%% freqtrade-strategy-tensorflow-data-validation
%% freqtrade-strategy-tensorflow-probability
%% freqtrade-strategy-tensorflow-eagerpy
%% freqtrade-strategy-vectorbt
%% freqtrade-strategy-pytorch
%% freqtrade-strategy-jax
%% freqtrade-strategy-freqtrade
